name: Unit Testing

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Installation
      run: |
        npm i @nrwl/cli
        npm install nx -g
        npm install --frozen-lockfile --force

    - name: Test
      run: |
        nx test frontend-blogger 
        nx test backend-blogger